server:
  port: 8080
spring:
  application:
    name: config-server
  # profiles:
  # active: native
  cloud:
    config:
      # server:
      # native:
      # search-locations: classpath:/config
      server:
        #git 配置项
        git:
          uri: https://gitee.com/routech/spring-cloud-config.git/
          search-paths: /config
        name: config-client
        profile: master